name: Fetch and Create MR

on:
  schedule:
    - cron: "0 6 * * 1" # Runs every Monday at 6 AM UTC
  workflow_dispatch: # Allows manual execution from GitHub Actions
  push:
    tags:
      - "manual-update" # Runs when this tag is pushed

jobs:
  fetch-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run Python script
        run: python scripts/__main__.py

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Stop Workflow if No Changes
        if: env.changes_detected == 'false'
        run: |
          echo "No changes detected. Exiting workflow."
          exit 0

      - name: Define PR Branch Name
        id: define_branch
        run: echo "BRANCH_NAME=update-generated-files-$(date +%Y-%m-%d-%H%M%S)" >> $GITHUB_ENV

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: master
          title: "Automated Update: Generated Files"
          body: "This PR contains the latest automated updates from `scripts/__main__.py`."
          labels: "auto-update"
          draft: false
