name: Fetch and Create MR

on:
  schedule:
    - cron: "0 6 * * 1" # Runs daily at 6 AM UTC (adjust as needed)
  workflow_dispatch: # Allows manual execution from GitHub Actions
  push:
    tags:
      - "manual-update" # Runs when this tag is pushed

jobs:
  fetch-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Adjust as needed

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run Python script
        run: python scripts/__main__.py

      - name: Check for changes
        id: check_changes
        run: |
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
          fi

      - name: Create a new branch (if changes exist)
        if: env.changes_detected == 'true'
        run: |
          BRANCH_NAME="update-generated-files-$(date +%Y-%m-%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Automated update: Generated files"
          git push origin "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create a Pull Request
        if: env.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "Automated Update: Generated Files"
          body: "This PR contains the latest automated updates from `scripts/__main__.py`."
          labels: "auto-update"
          draft: false
